#!/bin/bash -x

set -e

echo -e "\033[1;33mTo observe the database logs, run the command below:\033[1;m"
echo docker-compose logs --no-color --tail 99 -f pg | sed 's/.* | //'

set -a
source .env
set +a
./mvnw -f backend spring-boot:run
