#!/bin/bash

set -e

abortOnRepoNotClean() {
  if [ -n "$(git status --porcelain)" ]; then
    echo "$1 repo is not clean, aborting!"
    exit 1
  fi
}

abortOnRepoNotClean "Backend"
echo "--> Backend repo is clean..."

cd ../my-budget-ng/
abortOnRepoNotClean "Frontend"
echo "--> Frontend repo is clean..."
echo "--> Building Angular..."
ng build --configuration production
echo "--> Copying the build to the backend's static directory..."
cp -v ./dist/my-budget-ng/* ../my_budget_sb/src/main/resources/static/

cd -
echo "--> Copying to the static directory..."
git add ./src/main/resources/static/

echo "--> Committing the new build..."
git commit -m 'Angular build'
